staketogether/st-v1-interface

- package.json
- pnpm-lock.yaml
- src/components/explore/ExploreCard.tsx
- src/components/shared/wallet/WalletSidebar.tsx
- src/components/stake/StakeStats.tsx
- src/config/chain.ts
- src/hooks/contracts/useDeposit.tsx
- src/hooks/subgraphs/useAccountDelegations.tsx
- src/hooks/subgraphs/useStAccount.tsx
- src/hooks/subgraphs/useStAccountDelegations.tsx
- src/locales/en/common.json
- src/queries/queryAccount.ts
- src/queries/queryAccountDelegations.ts
- src/queries/queryCommunities.ts
- src/queries/queryCommunitiesDelegations.ts
- src/queries/queryCommunity.ts
- src/types/Account.ts
- src/types/Community.ts
- src/types/Delegation.ts
account.sentDelegationsCount
account.balance
community.receivedDelegationsCount
community.delegatedBalance
> Feat: Integrate new subgraph fields

- src/hooks/contracts/usePooledEthByShares.tsx
- src/hooks/subgraphs/usePool.tsx
> fix loading icon

- src/hooks/contracts/useDeposit.tsx
- src/hooks/contracts/useWithdraw.tsx
- src/hooks/useEstimateGas.tsx
> fix: estimate gas

- .cspell.json
- src/components/shared/ens/EnsName.tsx
- src/components/stake/StakeForm.tsx
- src/components/stake/StakeInput.tsx
- src/components/stake/StakePoolInfo.tsx
- src/hooks/contracts/useWithdraw.tsx
- src/hooks/useEstimateGas.tsx
- src/locales/en/common.json
- src/locales/pt/common.json
> feat: add rewards pool in view, isn't integration

- pnpm-lock.yaml
- src/components/stake/StakeActivity.tsx
- src/components/stake/StakePoolInfo.tsx
- src/config/chain.ts
- src/hooks/subgraphs/usePoolActivities.tsx
- src/pages/invest/deposit/[address].tsx
- src/pages/invest/withdraw/[address].tsx
- src/queries/subgraph/queryPoolActivities.ts
- src/services/truncate.ts
- src/types/PoolActivity.ts
> feat: added account column on pool activities

- src/components/invest/PoolsCard.tsx
- src/components/invest/PoolsControl.tsx
- src/components/invest/PoolsRowList.tsx
- src/components/shared/community/CommunityName.tsx
- src/locales/en/common.json
- src/locales/pt/common.json
- src/queries/subgraph/queryPools.ts
- src/types/Pool.ts
> feat: add rewards on list and cards

- src/components/stake/StakeWithdrawSwitchTypes.tsx
- src/components/wallet/WalletSidebarConnected.tsx
- src/locales/en/common.json
- src/locales/pt/common.json
> feat: add background on wallet button when account is connected

- src/components/shared/Tabs.tsx
- src/components/stake/StakeControl.tsx
- src/components/stake/StakeExchange.tsx
- src/locales/en/common.json
- src/locales/pt/common.json
> feat: add  tooltip message and fix form

- src/services/truncate.ts
> feat: add treatment for very low values

- src/components/incentives/IncentivesControl.tsx
- src/components/incentives/NextAirdropCountdown.tsx
> feat: add mobile on incentives page

- src/components/invest/PoolFilterIcon.tsx
- src/components/invest/PoolsControl.tsx
- src/components/stake/StakeControl.tsx
- src/hooks/subgraphs/useDelegationShares.tsx
- src/hooks/usePoolTypeTranslation.tsx
- src/locales/en/common.json
- src/locales/pt/common.json
- src/services/truncate.ts
> fix:  small fixes

- src/components/stake/StakeConfirmModal.tsx
- src/components/stake/StakeDescriptionCheckout.tsx
- src/components/stake/StakeForm.tsx
- src/components/stake/StakePoolAbout.tsx
> feat: fix exchange rate

- src/components/invest/PoolsControl.tsx
> feat: add quotation value

- src/components/shared/Button.tsx
- src/components/shared/RouletteComponent.tsx
- src/components/shared/WalletLottery.tsx
- src/components/stake/StakeControl.tsx
- src/components/wallet/WalletSidebarConnected.tsx
- src/components/wallet/WalletSidebarRewards.tsx
- src/locales/en/common.json
- src/locales/pt/common.json
- src/queries/subgraph/queryDelegationsPool.tsx
> feat: add multiply on profit value and fix format values

- src/components/wallet/WalletSidebarSettings.tsx
> feat: add check icon on settings sidebar

- src/components/stake/StakeActivity.tsx
- src/components/stake/StakeControl.tsx
- src/components/stake/StakePoolInfo.tsx
- src/components/stake/StakePoolMembers.tsx
- src/hooks/subgraphs/usePool.tsx
- src/hooks/subgraphs/usePoolActivities.tsx
- src/queries/subgraph/queryPool.ts
- src/types/Pool.ts
> feat: add paginate on activity pool

- src/components/stake/StakeExchange.tsx
- src/locales/en/common.json
- src/locales/pt/common.json
- src/pages/[network]/[currency]/invest/exchange/[address].tsx
- src/pages/api/faucet.ts
validate ip message -> Your Ip has already received ETH
> feat: add validate wallet balance and user  per ip for the faucet

- src/components/shared/community/CommunityLogo.tsx
- src/components/shared/community/CommunityName.tsx
- src/components/stake/StakeControl.tsx
- src/components/wallet/WalletSidebarPoolsDelegated.tsx
- src/queries/subgraph/queryPool.ts
- src/types/Pool.ts
> feat: add empty not listed

- src/components/stake/StakeForm.tsx
- src/components/stake/StakeWithdrawSwitchTypes.tsx
> feat: add validation on withdraw type

- src/pages/[network]/[currency]/invest/withdraw/[address].tsx
> fix: fix withdraw page

- src/components/project/ProjectRegisterInfo.tsx
- src/components/shared/ConfirmTermsModal.tsx
- src/components/shared/layout/LayoutHeaderDesktop.tsx
- src/components/shared/layout/LayoutHeaderMobile.tsx
- src/components/shared/layout/LayoutSidebarMobileMenu.tsx
- src/components/shared/layout/LayoutTemplate.tsx
- src/components/stake/StakePoolAbout.tsx
- src/config/global.ts
- src/hooks/useConfirmTermsModal.tsx
- src/locales/en/common.json
- src/locales/pt/common.json
- src/pages/api/project/setAgreeTermsOfUser.ts
- src/queries/contentful/queryContentfulPoolByAddress.ts
- src/types/ContentfulPool.ts
> feat: add terms of user

- next.config.js
- src/components/shared/layout/LayoutTemplate.tsx
- src/locales/en/common.json
- src/locales/pt/common.json
> feat: add deprecated

- src/components/shared/layout/LayoutTemplate.tsx
- src/locales/en/common.json
- src/locales/pt/common.json
> feat: added the graph indexing issue warning

- package.json
- pnpm-lock.yaml
Changes:
- removed no ssr package and update pnpm.lock
> fix: fix rango-widget build

- src/components/stake/StakeConfirmModal.tsx
> fix: icon stake

- src/components/assets/AssetsControl.tsx
- src/components/assets/AssetsSwap.tsx
- src/components/shared/NavActions.tsx
update asset details page, added new element showing current price
> feat: assets detail mobile

- src/components/new-stake/ethereum/EthereumInput.tsx
- src/components/new-stake/ethereum/EthereumShowReceiveCoin.tsx
add input mode decimal for mobile
> feat: add input mode for mobile

- src/components/new-stake/ProductInfo.tsx
- src/hooks/subgraphs/useAccountStPoints.tsx
- src/queries/subgraph/queryAccountStPoints.ts
create hook, search in graphsql for points and show in screen
> feat/ add st points

- src/components/shared/AssetPrice.tsx
fixed bug showing zero on rendering asset
> fix: fix asset price logic

- src/components/wallet/WalletSidebarAsset.tsx
fix wallet sidebar redirect currency
> fix: fix wallet sidebar redirect
